ENCODER:
  MEL_SPECTROGRAM:
    MEL_WINDOW_WIDTH: 25
    MEL_WINDOW_STEP: 10
    MEL_CHANNELS_COUNT: 40
    FRAMES_MIN_COUNT: 256
  PREPROCESSING:
    SAMPLING_RATE: 16000
    AMPLITUDE_DBFS: -30
    VAD_WINDOW_MS: 30
    VAD_MOVING_AVG_WIDTH: 8
  TRAINING:
    CHECKPOINT_FREQUENCY: 2
    TRAINING_ITERATIONS_COUNT: 2
    MELS_PER_TRAINING_ITERATION: 4
    INIT_LEARNING_RATE: 0.0001
  MODEL:
    LAYERS_COUNT: 3
    HIDDEN_LAYER_SIZE: 256
    EMBEDDING_SIZE: 256
