ENCODER:
  MEL_SPECTROGRAM:
    MEL_WINDOW_WIDTH_MS: 25
    MEL_WINDOW_STEP_MS: 10
    MEL_CHANNELS_COUNT: 40
    FRAMES_MIN_COUNT: 256
  PREPROCESSING:
    SHOULD_PREPROCESS: True
    SAMPLING_RATE: 16000
    AMPLITUDE_DBFS: -30
    VAD_WINDOW_MS: 30
    MAX_SILENCE: 6
    VAD_MOVING_AVG_WIDTH: 8
  TRAINING:
    CHECKPOINT_FREQUENCY: 1
    TRAINING_ITERATIONS_COUNT: 100
    SPEAKERS_PER_ITERATION: 64
    MELS_PER_SPEAKER: 10
    INIT_LEARNING_RATE: 0.0001
  MODEL:
    LAYERS_COUNT: 3
    HIDDEN_LAYER_SIZE: 256
    EMBEDDING_SIZE: 256
SYNTHESIZER:
  MEL_SPECTROGRAM:
    
  PREPROCESSING:
    RESCALE: True
    RESCALE_MAX: 0.9
    TRIM_SILENCE: True
    INT16_MAX: 32767
    VAD_WINDOW_LENGTH: 30  
    VAD_MOVING_AVERAGE_WIDTH:  8
    VAD_MAX_SILENCE_LENGTH: 6
    FMIN: 55
    FMAX: 7600
    HOP_LENGTH: 200
    WIN_LENGTH: 800
    MIN_LEVEL_DB: -100
    MAX_ABS_VALUE: 4.
    PREEMPHASIS: 0.97
   
  TACTRON:
    REF_LEVEL_DB: 20
    # Embedding dimension for the graphemes/phoneme inputs
    NUM_MELS: 80
    EMBED_DIMS: 512
    ENCODER_DIMS: 256
    DECODER_DIMS: 128
    POSTNET_DIMS: 512
    ENCODER_K: 5
    LSTM_DIMS: 1024
    POSTNET_K: 5
    NUM_HIGHWAYS: 4
    DROPOUT: 0.5
    STOP_THRESHOLD: -3.4
    N_FFT: 800
    
  TRAINING:
    BATCH_SIZE: 1
    SYNTHESIS_BATCH_SIZE: 16
    SPEAKER_EMBEDDING_SIZE: 256
  MODEL:
    LAYERS_COUNT: 3
    HIDDEN_LAYER_SIZE: 256
    EMBEDDING_SIZE: 256

